### ISSUE TITLE
Admin link does not work

### ISSUE THREAD

**Issue by philipbl** [corbinday/BYU-2017-theme-for-Dokuwiki#1]
Thanks for the great template! 

I am using a relative link to my wiki: `http://<host_name>/wiki`. When I click the "Admin" link, it removes the `wiki` part (goes to the root directory). All of the other toolbar links work fine.

**Comment by corbinday** [comment]
Reinstalling the template through the admin control panel will fix this problem for anyone else currently with this bug. To access the admin page, going to http://<hostname>/dokuwiki/doku.php?id=user:admin:start&do=admin&page=extension&tab=templates should get you to the right page.
